name: Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.8'
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app
      
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
          
    - name: Install Ruby Gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install Node Modules
      run: npm ci
    
    - name: Generate User Scripts
      run: npm run build-user-scripts

    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
          
    - name: Update Pods
      run: pod repo update
          
    - name: Install Cocoa Pods
      run: bundle exec pod install
    
    - name: Build and test
      run: xcodebuild clean test -workspace UserAgent.xcworkspace -scheme 'Cliqz' -configuration CI -sdk iphonesimulator -derivedDataPath builds -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11' -showBuildTimingSummary  
